name: Pull Request Validation
on:
  pull_request:
    branches: [ main ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run gradle check
        id: gradle
        run: ./gradlew check
