name: Run Verification on Pull Requests
on:
  pull_request:
    branches: [ main ]
jobs:
  gradle:
    name: Pull Request Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Check with Gradle wrapper
        id: gradle
        run: ./gradlew check
