name: Pull Request Validation
on:
  pull_request:
    branches: [ main ]
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Validate Gradle
        uses: gradle/wrapper-validation-action@v1
      - name: Run Validation
        run: ./gradlew check
